/*
 *  This file is covered by the Ruby license. See LICENSE.txt for more details.
 *
 *  Copyright (C) 2007-2012 Noam Chitayat. All rights reserved.
 */

#ifndef HOME_MENU_H
#define HOME_MENU_H

#include "MenuState.h"
#include "ModuleSelectListener.h"
#include "MenuAction.h"
#include <stack>
#include <map>
#include "guichan.hpp"

namespace edwt
{
   class StringListModel;
   class ListBox;
   class Label;
   class OpenGLTrueTypeFont;
   class Container;
   class TabbedArea;
};

class PlayerData;
class Sound;
class MenuShell;

/**
 * The home menu is the first menu state of the menu.
 * It serves to summarize important information for the player and allows the player to select
 * a character to perform further actions on.
 *
 * @author Noam Chitayat
 */
class HomeMenu: public MenuState, public edwt::ModuleSelectListener, public gcn::ActionListener
{
   /** The player data */
   PlayerData& playerData;

   /** The character-dependent action that is in queue after a character is selected */
   MenuAction characterAction;

   /**
    * Poll for and handle the input event.
    *
    * @param finishState Returned as true if the input event quit out of the main HomeMenu.
    */
   void pollInputEvent(bool& finishState);

   /**
    * @return true iff the action requires a character to be selected
    */
   bool isCharacterDependent(MenuAction action);

   protected:
      /**
       * Perform logic for the HomeMenu screen.
       * NOTE: this method will spin wait until user input is received.
       * Since the screen is static, there is no need to refresh without input.
       *
       * @return true iff the title screen is not finished running (no quit event)
       */
      bool step();

   public:
      /**
       * Constructor.
       *
       * Initializes the HomeMenu widgets, font, image and sounds
       *
       * @param executionStack The execution stack that the state belongs to.
       * @param menuShell The shell to display the GUI in.
       * @param playerData The player data to operate on.
       */
      HomeMenu(ExecutionStack& executionStack, MenuShell& top, PlayerData& playerData);

      /**
       * Called when a character is selected from the home pane.
       *
       * @param index the index of the character that was selected
       */
      void moduleSelected(int index, const std::string& eventId);

      /**
       * Called when a new tab in a tabbed area is selected.
       *
       * @param index The index of the tab that was selected.
       */
      void tabChanged(int index);
      
      /**
       * Called when the main menu receives a GUI action event.
       * Currently, only the listbox sends action events to the main menu.
       *
       * @param event The action event generated by the GUI.
       */
      void action(const gcn::ActionEvent& event);

      /**
       * Show the specified panel, and hide the currently active panel.
       */
      void showPanel(MenuAction panelToShow);

      /**
       * Destructor.
       */
      ~HomeMenu();
};

#endif
