/**
 *  This file is covered by the Ruby license. See LICENSE.txt for more details.
 *
 *  Copyright (C) 2007-2011 Noam Chitayat. All rights reserved.
 */

#ifndef MAIN_MENU_H
#define MAIN_MENU_H

#include "GameState.h"
#include "guichan.hpp"

namespace edwt
{
   class StringListModel;
   class ListBox;
   class Label;
   class OpenGLTrueTypeFont;
};

class Music;
class Sound;

/**
 * Provides the title screen functionality, including the game logo, backdrop, 
 * and options for the user.
 * This state is the first that the user must interact with.
 *
 * @author Noam Chitayat
 */
class MainMenu: public GameState, public gcn::ActionListener, public gcn::SelectionListener
{
   /** Main menu music */
   Music* music;

   /** Sound for hovering over an option */
   Sound* reselectSound;

   /** Sound for picking an option */
   Sound* chooseSound;

   /** The main title on top of the title screen */
   edwt::Label* titleLabel;

   /** The list box for all options in the title screen */
   edwt::ListBox* actionsListBox;

   /** The container for the background image */
   gcn::Icon* bg;

   /** The list model holding the options for the title screen */
   edwt::StringListModel* titleOps;

   /** The font for the title screen heading */
   edwt::OpenGLTrueTypeFont* titleFont;

   /** The font for the title screen menu options */
   edwt::OpenGLTrueTypeFont* actionsFont;

   /**
    * Populate the title screen list with required options
    */
   void populateOpsList();

   /**
    * Wait for and handle the input event.
    *
    * @param finishState Returned as true if the input event quit out of the main menu.
    */
   void waitForInputEvent(bool& finishState);

   //Actions for the list ops - see documentation in MainMenuActions.cpp
   void NewGameAction();
   void MenuPrototypeAction();
   void LoadGameAction();
   void OptionsAction();
   void AboutAction();
   void QuitAction();

   protected:
      /**
       * Waits a millisecond between draws (no rush on a title screen)
       */
      void draw();

      /**
       * Perform logic for the title screen.
       * NOTE: this method will spin infinitely until user input is received.
       * Since the screen is static, there is no need to refresh without input.
       *
       * @return true iff the title screen is not finished running (no quit event)
       */
      bool step();

   public:
      /**
       * Constructor.
       * Initializes the title screen widgets, font, image and sounds.
       *
       * @param executionStack The execution stack that the state belongs to.
       */
      MainMenu(ExecutionStack& executionStack);
   
      /**
       * When the state is activated, set modal focus to the listbox
       */
      void activate();
   
      /**
       * Called when the main menu receives a GUI reselection event.
       * Currently, only the listbox sends reselect events to the main menu.
       *
       * @param event The selection event generated by the GUI.
       */
      void valueChanged(const gcn::SelectionEvent& event);
   
      /**
       * Called when the main menu receives a GUI action event.
       * Currently, only the listbox sends action events to the main menu.
       *
       * @param event The action event generated by the GUI.
       */
      void action(const gcn::ActionEvent& event);
   
      /**
       * Destructor.
       */
      ~MainMenu();
};

#endif
